version: "3"
services:
  iofog-connector:
    build: ./iofog-connector
    ports:
      - "53321:8080"
    container_name: iofog-connector
    network_mode: bridge
  iofog-controller:
    build: ./iofog-controller
    depends_on:
      - iofog-connector
    ports:
      - "51121:51121"
    links:
      - iofog-connector
    container_name: iofog-controller
    environment:
      - NODE_ENV=development
    network_mode: bridge
  iofog-agent:
    build: ./iofog-agent
    depends_on:
      - iofog-controller
    links:
      - iofog-controller:iofog-controller
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: iofog-agent
    network_mode: bridge
